import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Abel, Inter } from 'next/font/google'
import "./globals.css";
import { Web3Provider } from "./Web3Provider";
import { ThirdwebProvider } from "thirdweb/react";
import { ThemeProvider } from "./contexts/ThemeContext";
import Footer from "../../components/Footer";
import Header from "@/components/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider>
          <Web3Provider>
            <ThemeProvider>
              <div className="flex flex-col min-h-screen">
                <Header />
                <main className="flex-grow">
                  {children}
                </main>
                <Footer />
              </div>
            </ThemeProvider>
          </Web3Provider>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
